kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: npm-data
  namespace: jenkins-k8s
spec:
  storageClassName: nfs-client
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi